scan_to_scan_filter_chain:
  ros__parameters:
    # filter1:
    #   name: footprint_filter
    #   type: laser_filters/LaserScanFootprintFilter
    #   params:
    #     inscribed_radius: 0.35

    # filter1:
    #   name: angle
    #   type: laser_filters/LaserScanAngularBoundsFilterInPlace
    #   params:
    #     lower_angle: -1.55
    #     upper_angle: 1.55

    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.0
        max_y: 0.3
        max_z: 0.3
        min_x: -0.6
        min_y: -0.3
        min_z: -0.3
        
        invert: false # activate to remove all points outside of the box
