scan_to_scan_filter_chain:
  ros__parameters:
    # filter1:
    #     name: box_filter
    #     type: laser_filters/LaserScanBoxFilter
    #     params:
    #       box_frame: base_link
    #       max_x: 0.4
    #       max_y: 0.4
    #       max_z: 0.3
    #       min_x: -0.5
    #       min_y: -0.4
    #       min_z: -0.3
          
    #       invert: false # activate to remove all points outside of the box

      # scan_filter_chain:
    filter1:
        name: angle
        type: laser_filters/LaserScanAngularBoundsFilterInPlace #laser_filters/LaserScanAngularBoundsFilter
        params:
          lower_angle: -1.57
          upper_angle: 1.57
    # filter2:
    #   name: shadows
    #   type: laser_filters/ScanShadowsFilter
    #   params:
    #     min_angle: 10.
    #     max_angle: 170.
    #     neighbors: 20
    #     window: 0
    # filter2:
    #   name: dark_shadows
    #   type: laser_filters/LaserScanIntensityFilter
    #   params: 
    #     lower_threshold: 100.
    #     upper_threshold: 10000.
    #     disp_histogram: 0


    filter2:
      name: footprint_filter
      type: laser_filters/LaserScanFootprintFilter
      params:
        inscribed_radius: 0.4

    # filter1:
    #   name: angular_bounds_filter
    #   type: laser_filters/LaserScanAngularBoundsFilter
    #   params:
    #     lower_angle: 3.
    #     upper_angle: 0.