mqtt_node:
  ros__parameters:
    robot_id: 1
    num_of_locations: 2
    location:
    # unfortunatelly it seems very complicated to parse 2d arrays
      location_id: [1,2]
      location_name: ["CONVEYOR_DECOCTION", "DECOCTION"]
      coordinate_x: [0.0, 0.0]
      coordinate_y: [0.0, 4.5]
      orientation_z: [0.0, 0.689]
      orientation_w: [1.0, 0.725]