mqtt_configuration:
  ros__parameters:
    broker:
      host: localhost #192.168.0.200
      port: 1883
    bridge:
      ros2mqtt:
        ros_topic: /robots/configuration
        mqtt_topic: robots/configuration
        primitive: true
      # mqtt2ros:
      #   mqtt_topic: robots/configuration
      #   ros_topic: /test/configuration

mqtt_status:
  ros__parameters:
    broker:
      host: localhost #192.168.0.200
      port: 1883
    bridge:
      ros2mqtt:
        ros_topic: /robots/id_1/status
        mqtt_topic: robots/id_1/status
        primitive: true
        advanced:
          mqtt:
            qos: 1
      # mqtt2ros:
      #   mqtt_topic: robots/id_1/status
      #   ros_topic: /test/id_1/status

mqtt_location:
  ros__parameters:
    broker:
      host: localhost #192.168.0.200
      port: 1883
    bridge:
      ros2mqtt:
        ros_topic: /robots/id_1/location
        mqtt_topic: robots/id_1/location
        primitive: true
      # mqtt2ros:
      #   mqtt_topic: robots/id_1/location
      #   ros_topic: /test/id_1/location