mqtt_client:
  ros__parameters:
    broker:
      host: localhost
      port: 1883
    bridge:
      ros2mqtt:
        ros_topic: /robots/configuration
        mqtt_topic: robots/configuration
      mqtt2ros:
        mqtt_topic: robots/configuration
        ros_topic: /pong/ros
